_target_: "monai.networks.nets.DynUNet"
in_channels: 1
out_channels: 9
spatial_dims: 3
strides: [[1, 1, 1], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]  # 5 levels
kernel_size: [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]
upsample_kernel_size: [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]
filters: [32, 64, 128, 256, 320]
res_block: True