_target_: src.model.MultiBackboneModel
model_name: "tf_efficientnetv2_s.in21k_ft_in1k"
pretrained: True
in_chans: 32
drop_rate: 0.3
drop_path_rate: 0.2
num_classes: 14
convlstm_hidden_dim: 64
reduce_seq_len: 64