_target_: src.model.MultiViewWaveletModel
model_name: "tf_efficientnetv2_b0.in1k" #RepVGG-B0,"ghostnetv2_100"(no drop_path_rate)
pretrained: True
drop_rate: 0.3
drop_path_rate: 0.2
k_candi: 2
model_dim: 512
transformer_layers: 2
transformer_heads: 8
classifier_hidden: 256
dropout: 0.2