defaults:
  - hydra: default
  - model: dyn_unet_base
  - _self_

# i/o
image_path: ./example
image_file_ending: nii
output_folder: ./output
file_app: ""

mask_path: null
round_to: 2

# model & ckpt
device: cuda:0
ckpt_path: /path/to/ckpt.pt

# sliding window inferer
batch_size: 1
patch_size: [128, 128, 128]
overlap: 0.75
mode: "constant"
sigma_scale: 0.125
padding_mode: "constant"

# eval & reproducibility
seed: 404

# standard pre-processing transforms
transforms_config:
  - EnsureChannelFirst:
      channel_dim: "no_channel"
  - ScaleIntensityRangePercentiles:
      lower: 1
      upper: 99
      b_min: 0
      b_max: 1
      clip: true
  - ToTensor:
      device: null

# test time augmentation
tta:
  scales: [1]
  invert: true
  invert_mean_thresh: 0.5
  equalize_hist: true
  hist_bins: 100

# post-processing
post:
  apply: false
  small_objects_min_size: 500
  small_objects_connectivity: 3

# merging
merging:
  threshold: 0.1
  max: false