# conf/config.yaml
# These are some base parameters for the experiment
project_name: "rsna-intracranial-aneurysm-detection"

data_dir: ./data/processed
seed: 42
fold_id: 0
batch_size: 4  
num_workers: 1  
experiment: naive_efficientnet_v2_cls

# Balanced sampling configuration
use_balanced_sampling: true  # Set to true to enable balanced pos/neg sampling
pos_ratio: 0.5  # 0.5 with batch_size 4 = 2 positive + 2 negative per batch
image_mode: "2.5D"
use_wandb: true  # Set to false to disable WandB logging

# WandB settings (only used if use_wandb: true)
wandb:
  entity: null  # Auto-detect from logged-in user
  tags: ["tf_efficientnetv2_b0.in1k", "fold_${fold_id}"]
  notes: "efficientnet_v2 on 2.5D slices"


# The 'defaults' list tells Hydra which configs to load by default.
# It will look for 'lightgbm.yaml' inside the 'model' sub-directory.
defaults:
  - model: MultiBackboneModel
  - optimizer: AdamW
  - trainer: default
  - _self_

