# conf/config.yaml
# These are some base parameters for the experiment
project_name: "rsna-intracranial-aneurysm-detection"
experiment: windowed_mip
seed: 42
fold_id: 1

params:
  data_path: ./data/processed
  batch_size: 12
  num_workers: 8


# The 'defaults' list tells Hydra which configs to load by default.
# It will look for 'lightgbm.yaml' inside the 'model' sub-directory.
defaults:
  - preprocess: segmentation
  - optimizer: AdamW
  - trainer: default
  - model: timm
  - _self_
