# conf/config.yaml
# These are some base parameters for the experiment
project_name: "rsna-intracranial-aneurysm-detection"
experiment: windowed_mip
seed: 42

# The 'defaults' list tells Hydra which configs to load by default.
# It will look for 'lightgbm.yaml' inside the 'model' sub-directory.
defaults:
  - preprocess: segmentation
  # - model: Net_25D
  # - optimizer: AdamW
  # - trainer: default
  # - _self_
