# conf/config.yaml
# These are some base parameters for the experiment
project_name: "32-ch-reproduce"
experiment: 32-ch-cnn
seed: 42
fold_id: 0
offline: true


params:
  data_dir: ./data
  num_classes: 14
  img_height: 512
  img_width: 512
  batch_size: 4
  num_workers: 8
  use_mip: False

  depth:
    mr: [0,32]
    ct: [0,32]


# The 'defaults' list tells Hydra which configs to load by default.
# It will look for 'lightgbm.yaml' inside the 'model' sub-directory.
defaults:
  - preprocess: default
  - optimizer: AdamW
  - trainer: default
  - model: timm
  - _self_
