# conf/config.yaml
# These are some base parameters for the experiment
project_name: "rsna-intracranial-aneurysm-detection"

data_dir: ./src/rsna_data/series_extraction_dense
meta_dir: ./src/rsna_data
offline: False
num_neighbs: 15
seed: 42
fold_id: 0
batch_size: 4
radius: 10
num_nodes: 2000
num_workers: 16
use_pe: True
walk_length: 4
experiment: vesselfm-graphsage-k15-w4

modality:
  - CTA
  - MRA
  - MRI T2
  - MRI T1post

defaults:
  - model: GraphModel
  - optimizer: AdamW
  - trainer: default
  - _self_
