# conf/config.yaml
# These are some base parameters for the experiment
project_name: "multi-view-model"
experiment: logpolar-mip-vol-3-views
seed: 42
fold_id: 1
offline: true


params:
  data_dir: ./src/data
  num_classes: 14
  img_height: 512
  img_width: 512
  batch_size: 4
  num_workers: 4
  use_mip: False

  depth:
    mr: [0,32]
    ct: [0,32]


# The 'defaults' list tells Hydra which configs to load by default.
# It will look for 'lightgbm.yaml' inside the 'model' sub-directory.
defaults:
  - preprocess: default
  - optimizer: AdamW
  - trainer: default
  - model: PatchModel
  - _self_
