# conf/config_slices.yaml
# Configuration for slice-based training (memory efficient)
project_name: "rsna-intracranial-aneurysm-detection-slices"

data_dir: ./data/processed
seed: 42
fold_id: 0
use_small_dataset: true  # null = train on all folds except fold_id, or specify list [0,1,2] for subset
batch_size: 4  # training batch size
val_batch_size: 4  # validation batch size
num_workers: 2  
experiment: slice_based
image_mode: "2D"  # Options: "2D" or "2.5D"

# 2.5D specific configuration (only used when image_mode = "2.5D")
# Use   window size. Example: 8 = center + 7 adjacent slices
window_size: 8
window_position_strategy: "random"  # Use "centered" to always center on target slice



# Balanced sampling configuration
use_balanced_sampling: true  # Set to true to enable balanced pos/neg sampling
pos_ratio: 0.95 # 0.75

use_wandb: true

# WandB settings
wandb:
  entity: null
  tags: ["baselinesv2", "slice_based", "fold_${fold_id}"]
  notes: "baselinesv2"

# The 'defaults' list tells Hydra which configs to load by default.
defaults:
  - model: MultiBackboneModel
  - optimizer: AdamW
  - trainer: default
  - _self_