# conf/config.yaml
# These are some base parameters for the experiment
project_name: "rsna-intracranial-aneurysm-detection"

data_dir: ./src/data/processed
seed: 42
fold_id: 0
batch_size: 8
num_workers: 8
experiment: vesselfm-graphsage

modality:
  - CTA
  - MRA
  - MRI T2
  - MRI T1post

defaults:
  - model: GraphModel
  - optimizer: AdamW
  - trainer: default
  - _self_
