# Parameters
nc: 80  # number of classes
scales:
  n: [1.00, 1.00, 512]
backbone:
  - [-1, 1, Timm, [1024, 'convnextv2_base.fcmae_ft_in22k_in1k', True, True, 0, True]]
  
  - [0, 1, Index, [128, 0]]  # 1: P2 -> 128 ch @ 240x240
  - [0, 1, Index, [256, 1]]  # 2: P3 → 256 ch @ 120x120
  - [0, 1, Index, [512, 2]]  # 3: P4 → 512 ch @ 60x60
  
  # SPPF + PSA on P4 (not P5)
  - [-1, 1, SPPF, [512, 5]]  # 4
  - [-1, 2, C2PSA, [512]]    # 5

head:
  - [5, 1, nn.Upsample, [None, 2, "nearest"]]  # 6: 512 ch @ 120x120
  - [1,1,AVG,[]] # 7: P2 128 ch @ 240x240 -> 128 ch @ 120x120
  - [[7, 2, 6], 1, Concat, [1]]                   # 8: 512+256=768 ch @ 120x120
  - [-1, 2, C3k2, [512, False]]                 # 9: 768 → 512 ch @ 120x120
  - [[-1], 1, Detect, [nc]]                     # Output