# Parameters
nc: 80  # number of classes
scales:
  n: [1.00, 1.00, 512]

backbone:
  - [-1, 1, Timm, [768, 'convnext_tiny.in12k_ft_in1k', True, True, 0, True]]
  
  - [0, 1, Index, [96, 0]]   # 1: P2 -> 96 ch @ 56x56
  - [0, 1, Index, [192, 1]]  # 2: P3 → 192 ch @ 28x28
  - [0, 1, Index, [384, 2]]  # 3: P4 → 384 ch @ 14x14
  
  # SPPF + PSA on P4 (not P5)
  - [-1, 1, SPPF, [384, 5]]  # 4: Keep 384 channels
  - [-1, 2, C2PSA, [384]]    # 5: Keep 384 channels

head:
  - [5, 1, nn.Upsample, [None, 2, "nearest"]]  # 6: 384 ch @ 28x28
  - [1, 1, AVG, []]                            # 7: P2 96 ch @ 56x56 -> 96 ch @ 28x28
  - [[7, 2, 6], 1, Concat, [1]]                # 8: 96+192+384=672 ch @ 28x28
  - [-1, 2, C3k2, [384, False]]                # 9: 672 → 384 ch @ 28x28
  - [[-1], 1, Detect, [nc]]                    # Output