defaults:
  - train
  - data: eval_rsna
  - override data: eval_rsna
  - _self_

num_shots: 0
lr: 0.00001
fold_idx: 0
threshold: 0.1
devices: [1]
run_name: vesselfm
path_to_chkpt: /path/to/pretrained_ckpt
chkpt_folder:  ./finetune_ckpts

dataloader:
  shuffle: False

trainer:
  lightning_trainer:
    val_check_interval: 20
    max_steps: 3000
    max_epochs: 50

  lightning_module:
    _target_: module.RSNAModuleFinetune
    _partial_: True
    prediction_threshold: 0.62
    batch_size: ${batch_size}
    input_size: ${input_size}

    optimizer_factory:
      _target_: torch.optim.Adam
      _partial_: True
      lr: 0.0001

    scheduler_configs:
      cosine_annealing_few:
        interval: step
        frequency: 10
        scheduler:
          _target_: torch.optim.lr_scheduler.CosineAnnealingLR
          _partial_: True
          T_max: 1000
          eta_min: 0.0000001
          last_epoch: -1

      linear_warmup: null 
      cosine_annealing: null