defaults:
  - data: real_drand_flow
  - trainer: default
  - model: dyn_unet_base
  - hydra: default
  - _self_

# data
input_size: [64, 64, 64]
image_channels: 1
num_classes: 1

# training
seed: 404
lr: 0.0001
batch_size: 4
eval_path: /path/to/eval_set_pretrain
path_to_chkpt: null
devices: [1]

# logging
run_name: 'fine-tune-seg'
wandb_project: 'rsna-intracranial-aneurysm'
chkpt_folder: /path/where/to/store/chkpts
offline: False

# dataloader
dataloader:
  _target_: "torch.utils.data.DataLoader"
  _partial_: True
  num_workers: 8
  prefetch_factor: 3
  batch_size: ${batch_size}
  pin_memory: True
  persistent_workers: True
  shuffle: True